Update smi_stream_dev.c
This fixes building on DragonOS_Pi64 - not sure if it breaks other OSes or not, though.

/home/ubuntu/cariboulite/driver/build/smi_stream_dev.c:1319:28: error: too many arguments to function ‘class_create’
 1319 |         smi_stream_class = class_create(THIS_MODULE, DEVICE_NAME);